version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fastapisam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ktktqxry1d4q"
s3_prefix = "fastapisam"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
